name: 'Check Issues Due Date'

on: workflow_dispatch
  
  #schedule:
   # - cron: '0 1 * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Check duedate and send email to assignees
        uses: petrandr/duedate_reminders@latest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_number: 2
          notify_for: "expiring_issues"
          duedate_field_name: "Deadline"
          notification_type: "email"
          smtp_server: ${{ secrets.SMTP_SERVER }}
          smtp_port: 587
          smtp_username: ${{secrets.SMTP_USERNAME}}
          smtp_password: ${{secrets.SMTP_PASSWORD}}
          smtp_from_email: assistailabs@gmail.com
          
